In [1]:
# import this library in j.notebook
import numpy as np



# creating an array using numpy


In [2]:
#1 D array
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [4]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [8]:
len(price)

3

In [9]:
len(food)

3

In [15]:
#indexing
price[2] #agar 3 likahin gy to error aye ga q k last exclusive hota hay

5

In [16]:
food[1]


'Samosa'

In [17]:
price.mean()

5.0

In [18]:
#zeros method array banany k liye
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [19]:
#one ki array banany k liye
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
#empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# specify a range
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [27]:
#specic interval in range
np.arange(2,20,2)# pehly 2 digits range and 3rd one is difference

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
#table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [37]:
#line space
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
#specify your data type
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [40]:
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# array sorting or array function


In [43]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [44]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [45]:
# concatinate two arrays
b = ([10,2.3,3.4, 91.6,45.5,53.6])
b

[10, 2.3, 3.4, 91.6, 45.5, 53.6]

In [50]:
c = np.concatenate((a,b))

c.sort()
c

array([  0.5,   2. ,   2.3,   3.4,   4. ,   6. ,  10. ,  10. ,  10.3,
        12. ,  15. ,  45.5,  53.6,  91.6, 100. , 320. ])

In [53]:
# 2-D arrays
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [54]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [55]:
c = np.concatenate((a,b)) # ye error dy ga q k arrays barabar nhn...dimension...axis lagana paray ga
c

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 2

In [56]:
b = np.array([[6,7,8,9,8],[8,9,5,4,3]])
b

array([[6, 7, 8, 9, 8],
       [8, 9, 5, 4, 3]])

In [61]:
c= np.concatenate((a,b), axis=0) # same tarteeb add ho gi..yani pehly pehli array phir dusri
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [6, 7, 8, 9, 8],
       [8, 9, 5, 4, 3]])

In [63]:
c= np.concatenate((a,b), axis=1) #jab axis 1 karian gy to  tarteeb ulti ho gi..yani dono arrays rows k hisab sy jama hon gi
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 8],
       [5, 4, 3, 2, 1, 8, 9, 5, 4, 3]])

In [66]:
a = np.array([[[0,1,2,3],
               [4,5,6,7]],
              [[0,1,2,3],
               [4,5,6,7]],
              [[0,1,2,3],
              [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [67]:
#how to find the number of dimension
a.ndim

3

In [73]:
--type(a)

type

In [68]:
b = np.array([[5,6,7],
              [8,9,10],
             [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [69]:
b.ndim

2

In [76]:
b.size # size (number of elements)

9

In [80]:
#shape 
b.shape

(3, 3)

In [83]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# arrray banany k bad bhi re shape kar sakty hain

In [85]:
a = a.reshape(3,3) #yani 3 rows and 3 column tarteeb sy ho jayen gy
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
# reshape
np.reshape(a, newshape=(1,9), order="C")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [91]:
# convert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
b = a[np.newaxis,:] # row wise 2D conversion
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [93]:
b.shape

(1, 9)

In [94]:
c = a[:,np.newaxis] # column wise 2 -D conversion
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [95]:
#indexing and slicing
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [101]:
a*6


array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [102]:
a.mean()

5.0