In [1]:
#one dimensional array
import numpy as np
a = np.array([5,5,5])
a

array([5, 5, 5])

In [2]:
type(a)

numpy.ndarray

In [3]:
len(a)

3

In [4]:
a[0]

5

In [5]:
a[0:]

array([5, 5, 5])

In [8]:
#List of lists
import numpy as np
b = np.array([[5,5,5],[3,3,3],[5,5,5]])
b


array([[5, 5, 5],
       [3, 3, 3],
       [5, 5, 5]])

In [9]:
type(b)

numpy.ndarray

In [10]:
len(b)

3

In [11]:
b[1]

array([3, 3, 3])

In [13]:
b[1:2]

array([[3, 3, 3]])

In [14]:
b[0:]

array([[5, 5, 5],
       [3, 3, 3],
       [5, 5, 5]])

In [16]:
c=np.array([[5,5,3],[3,2,1],[4,3,1]])
c

array([[5, 5, 3],
       [3, 2, 1],
       [4, 3, 1]])

In [17]:
e = np.arange(6) #aik specific range dy k bhi array bana sakty hain
e

array([0, 1, 2, 3, 4, 5])

In [19]:
g = np.arange(2,20,2) #aik range di hy 2 sy ly kar 20 tak...and 2 k difference sy
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
h = np.linspace(0,10, num=5) # ic ny 10 k ander same difference walay number pick kiye hain
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
#specific data types in array
i = np.ones(5,dtype=np.int8) # aik hi data k number pick kiye hain
i

array([1, 1, 1, 1, 1], dtype=int8)

In [25]:
j = np.ones(3,dtype=np.float64)
j

array([1., 1., 1.])

In [27]:
#2-D arrays
np.zeros((3,4)) #3 rows and 4 columns 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
#creat an array for 3-D
D = np.arange(24).reshape(2,3,4)
D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])